dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: patrykwitkowski-github
    token:
      secure: RtrrceBcfEGpB90XlKXJu+sKtYg1by0S8A2pI1xC+9i4+LdZq6d0a9etbPa3gGPXejWc8tYbN5/sVS/xucPC/qJarht+o1YV9OWRia3b03aTM140pR/TqxRC8wmo8Cbk4/E/KtrSlZvjpHmxc2swmdeRphUXaWhRgLV+GEozgrWE06YWaiwpUstryubCGBYoBH9Y8Mcybk6cF+t0Gp3CeC2IS5OlUyKniUyheKPFBg/0WVBtTr3y3fLx65AAGdkhtLmLRlHZ/1O5azddJ21hCHOknyhbhA4D8lcvcEVUBZ3BsOoO3marmTaTX2pfQf2WlWBaeqmqgl9TSAVVJQQz+BoFxBchbrYv2i7p+QI++JlXCnH/gtNh14nbkYWWDYmnVOe89KxwZqwJ3WtJIE/4mXe8vaXHubv53lZu9Q5mOxPf+8JPlyEVaGkxWfgCYzkZWcOPGE14lzSB1kawmU22VmWP30f2l3+bfRjUm3+Ux+Xs4lQ3TGd6RpzJC+xj3gj7xyqO4AAaNXKJO0po+ieIvfOrasIojdbwYNiNC2FztxRqsIHD5V6AdatPipcJecBHonXRR5GIytQfe/LEljWqxqMxm+tEd641C5UpAe6ze2iOPaej04EX75D7HWoEvYwr+694OlKFOdX9g6JNGFGnr6NrkMu2Lnb+EKK4PHQNRZE=
language: java
jdk:
- oraclejdk8
script:
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
deploy:
  provider: heroku
  api_key:
    secure: kTYGoF1Y/Y2ixwfEPj09snvXt2NTDJGpjh1wPyooTd0s/eDPFWEdc5g8OmJrfC0gfH+JqkOYF0dpbrhSJ8LBmgsbAUuC1Q4D+a1MtceRmQRSQzNOiOt+0MTebMxyUtHLDwGMQ3IekS4jtDDa0vfoU9zeZhXQPHjDDlXGR0E4f9g0kXUwKRQA+N8RYhVFYULnNrNJpMktQXtpK1/gZ0L9GfRm6FWApe5Du7C0iRRGKOAsncC1TEW+hk+54L4Omlm86mj1RNJTciREANZjjiHi9pjM9HqJ1uC+/e4Dx8jpFUcEVkiqr26r5KHx/6Jr7ZWnLHxDn8uLBlBfMPeeok3jcFAuLu8PFLk6n0AY94/qI5fYbDGEMvgk6UY5DwL7Lhlmb8G/ASHreW8YlnRnenkVLhM6CspaqNW4/2KvRaHtmDt336RpIXQWa4y86NzkmJzLkDJYPBKq7yfog5bxxMH3823ZTWJtGe29fmSuFfb1T8tix/giQ2pj9xQSQ+RcueqkacYaGFACigQLxpKj/sqoc6gD7MT22T72zIbul7sDmcuENEbSl/pwmUBebb5WwiVHhCY4gyGCJ2m0SEIlJB2bSmrwFPa1+5/VB6uYBrAOqrQcZKm+w1leKR74LPcGsTol0BInzGMhQZxWWo1oeiQzG4EBOku5FoqNjTPZSuXPyoo=
  app: order-manager
  on:
    repo: PatrykWitkowski/order-manager
